# Welcome to Jekyll!

# Website settings
title: "Jistol"
description: "Jistol Development Github Page"
keywords: ""
baseurl: "/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Jistol'
  first_name: 'Kim'
  last_name: 'ji hwan'
  email: 'pptwenty@gmail.com'
  facebook_username: 'JistolKim'
  github_username: 'jistol'
  avatar: 'static/img/landing/Jack.jpg'
  desc: 'Wating...'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jistol-github-io
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
