# Site Info
title: Rohit Joshi's Homepage
tagline: RohitRox @ TheInternet
description: All about Rohit Joshi and his tech stuff
baseurl: ""
url: "http://rohitrox.github.io"
lang: en
# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss

paginate: 5

permalink: /:year/:month/:day/:title/

version: 1.0.0

# About/contact
author:
  name: Rohit Joshi
  description: Full Stack Software Developer
  contact:
    linkedin:  https://www.linkedin.com/in/rohitrox
    github:    https://github.com/rohitrox
    twitter:   https://twitter.com/roxxypoxxy
    email:

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Categories:
    - '/categories/'
  Tags:
    - '/tags/'
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'
# Puglins
mathjax: true # whether support mathjax
# leave blank if you don't want google analytics
google_analytics_token:
naver_analytics_token:
disqus_short_name: 'webdevelopmentlog' # leave blank if you don't want disqus
